baseURL = 'https://almstueberlmusi.at/'
locale = 'de-at'

title = 'Almstüberl Musi'
theme = "bienensteff"

[params.main]
  img = "avatar.jpg"
  icon = "avatar.jpg"

[menus]
[[menus.main]]
name = "Booking"
pageRef = "/booking"
weight = 10

[[menus.main]]
name = "Veranstaltungen"
pageRef = "/veranstaltungen"
weight = 20

[[menus.main]]
name = "Galerie"
pageRef = "/galerie"
weight = 30

[[menus.main]]
name = "Über uns"
pageRef = "/über-uns"
weight = 40

[[menus.footer]]
pre = '<i class="bi bi-instagram"></i>'
name = 'Instagram'
URL = 'https://www.instagram.com/almstueberl_musi'
weight = 10

[[menus.footer]]
name = 'Impressum'
pageRef = '/impressum'
weight = 20

[[menus.footer]]
name = 'Datenschutz'
pageRef = '/datenschutz'
weight = 30


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '„'
        leftSingleQuote = '‚'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '”'
        rightSingleQuote = '‘' 

[imaging]
  quality = 97
  resampleFilter = "Lanczos"

[security]
  enableInlineShortcodes = true
